14:06:08.370 INFO  Ob received and saved into database for dict_keys(['btcpln', 'ethpln', 'lunapln', 'ftmpln']) 
14:06:13.774 INFO  Ob received and saved into database for dict_keys(['btcpln', 'ethpln', 'lunapln', 'ftmpln']) 
14:06:19.165 INFO  Ob received and saved into database for dict_keys(['btcpln', 'ethpln', 'lunapln', 'ftmpln']) 
14:06:24.611 INFO  Ob received and saved into database for dict_keys(['btcpln', 'ethpln', 'lunapln', 'ftmpln']) 
14:09:41.138 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:09:46.510 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:09:51.938 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:09:57.514 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:10:02.864 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:10:08.279 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:10:13.629 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:10:18.972 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:11:45.315 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:11:49.973 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:11:55.101 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:00.198 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:05.086 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:10.049 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:15.092 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:20.087 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:25.136 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:30.199 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:35.200 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:40.123 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
14:12:47.324 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
19:18:17.787 ERROR   $$ 'message' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 29, in main
    '{str(dict_val['message']['transactions'][0]['id'])}',
KeyError: 'message'
19:18:21.157 INFO  Trades received on timestamp: 1642789100953
19:18:46.702 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:46.749 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:46.811 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:46.858 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:46.905 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:46.952 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.061 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.124 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.202 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.249 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.296 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.343 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.421 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.499 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.562 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.843 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.921 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:47.968 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.046 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.124 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.186 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.254 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.286 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.379 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.473 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.535 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.582 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.645 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.707 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.770 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.848 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.942 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:48.989 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.035 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.098 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.161 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.223 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.473 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.525 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.603 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.650 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.728 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.775 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.822 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.869 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:49.947 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.009 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.056 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.166 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.228 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.291 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.353 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.463 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.525 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.572 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.650 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.728 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.775 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:50.838 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.062 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.155 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.280 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.358 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.421 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.515 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.577 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.640 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.671 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.733 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.780 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.827 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.874 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:18:51.942 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 58, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:12.848 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:12.910 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.004 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.051 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.129 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.176 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.223 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.286 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.364 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.457 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.505 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.551 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.614 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.661 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.725 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.759 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.822 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.869 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:13.947 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.011 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.058 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.120 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.172 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.235 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.282 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.329 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.407 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.485 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.532 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.594 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.641 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.688 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.735 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.782 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.844 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:14.907 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.001 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.063 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.128 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.162 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.225 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.287 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.334 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.412 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.459 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.506 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.574 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.636 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.683 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.746 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.808 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.871 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:15.965 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.012 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.058 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.152 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.215 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.261 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.355 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.433 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.496 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.574 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:16.621 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:54.999 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.051 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.114 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.161 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.207 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.254 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.317 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.645 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.754 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.817 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:55.864 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.176 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.239 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.301 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.348 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.414 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.478 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.510 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.557 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.604 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.651 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.713 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.760 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.807 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.932 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:56.979 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.041 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.072 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.119 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.166 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.197 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.260 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.307 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.369 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.432 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.479 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.541 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.588 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.635 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.697 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.744 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.796 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.828 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.875 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.921 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:57.953 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:58.046 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:58.093 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:19:58.156 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:40.809 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:40.872 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:40.966 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.028 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.091 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.153 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.231 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.278 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.325 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.388 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.456 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.518 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.581 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.628 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.706 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.752 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.799 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.846 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:41.956 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.003 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.065 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.143 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.206 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.253 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.300 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.362 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.487 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.534 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.596 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.643 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.690 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.768 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.820 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.883 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:42.945 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.008 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.054 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.101 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.179 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.242 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.289 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.351 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.414 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.476 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.523 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.570 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.633 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.695 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.742 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.804 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.851 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.914 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:43.976 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.025 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.118 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.202 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.249 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.296 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.358 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.436 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.593 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.655 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.733 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.879 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:44.957 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.020 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.051 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.098 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.176 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.301 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.354 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.447 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.494 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.541 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.604 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.650 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.713 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.775 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.822 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.869 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.947 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:45.994 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.072 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.135 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.213 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.260 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.307 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.354 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.432 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.494 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.541 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.604 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.666 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.713 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.760 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.822 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:46.875 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.031 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.188 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.234 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.281 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.328 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.391 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.438 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.500 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.578 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.641 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.734 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.797 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.844 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.891 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:47.953 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.016 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.078 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.125 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.172 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.219 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.271 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.552 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.599 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.646 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.787 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.881 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:48.943 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.006 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.053 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.177 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.240 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.318 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.412 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.490 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.537 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.605 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.667 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.714 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.777 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.823 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.886 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:49.964 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.011 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.073 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.151 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.199 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.277 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.324 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.407 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.469 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.532 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.579 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.626 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.704 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.766 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.844 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.922 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:50.974 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.021 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.084 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.131 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.193 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.240 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.318 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.464 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.527 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.589 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.636 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.746 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.793 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.839 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.902 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.949 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:51.996 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.277 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.360 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.454 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.563 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.642 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.751 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.798 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.860 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:52.938 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.032 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.095 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.157 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.204 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.251 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.360 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:20:53.438 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 59, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.433 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.465 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.527 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.590 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.652 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.699 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.762 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.840 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.933 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:01.996 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.059 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.168 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.246 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.308 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.559 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.621 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.668 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.715 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.765 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.814 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.876 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:02.954 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.002 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.079 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.126 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.173 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.220 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.283 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.345 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.455 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.501 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.548 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.611 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.658 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.720 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.767 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.798 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.845 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.923 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:03.955 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.001 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.080 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.147 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.225 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.303 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.350 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.428 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.475 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.538 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.600 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.647 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.741 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.804 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.897 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:04.975 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.022 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.069 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.116 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.179 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.225 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.288 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:23:05.350 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:16.716 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:16.794 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:16.951 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:16.998 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.044 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.107 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.170 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.232 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.295 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.341 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.451 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.513 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.576 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.638 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.722 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.784 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.847 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.941 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:17.987 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.050 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.097 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.144 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.206 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.253 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.331 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.456 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.519 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.597 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.659 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.764 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.826 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.951 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:18.998 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.061 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.144 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.191 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.238 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.300 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.362 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.519 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.581 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.644 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.706 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.753 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.800 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.863 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:19.972 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.050 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.113 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.160 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.206 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.269 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.331 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.442 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.492 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.540 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.602 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.711 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.758 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.805 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:25:20.868 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 61, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:31.747 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:31.821 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:31.928 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.008 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.078 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.152 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.198 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.245 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.301 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.353 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.449 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.529 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.592 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.648 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.697 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.775 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.858 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:32.955 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.004 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.059 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.114 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.164 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.211 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.285 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.350 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.466 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.520 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.571 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.617 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.668 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.715 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.776 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.840 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:33.955 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.009 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.097 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.147 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.189 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.254 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.308 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.366 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.447 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.493 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.612 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.666 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.713 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.778 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.847 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:34.953 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:35.008 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:35.062 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:35.120 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:35.188 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:35.257 ERROR   $$ 'sell' $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_ob.py", line 60, in main
    '{str(response_dict[k]['sell'][0]['ra'])}',
KeyError: 'sell'
19:39:58.277 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
19:40:03.152 INFO  Ob received and saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:23:36.322 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:23:41.334 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:23:46.342 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:23:51.352 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:23:56.365 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:01.386 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:06.398 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:11.409 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:16.425 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:21.429 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:26.441 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:31.455 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:36.459 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:41.468 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:46.481 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:51.493 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:24:56.510 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:25:01.522 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:25:06.544 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:25:11.555 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:39:45.527 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:39:50.548 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:39:55.550 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:40:00.567 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:44:09.326 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:44:14.336 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:44:19.346 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:44:24.351 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:58:35.067 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:59:36.772 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
20:59:41.789 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:00:10.486 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:00:15.499 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:00:20.500 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:00:25.505 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:00:30.516 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:01:54.075 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:01:59.083 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:04.096 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:09.106 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:14.120 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:19.138 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:24.155 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:29.173 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:34.184 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:39.200 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:44.214 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:02:49.221 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:30.608 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:35.622 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:40.640 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:45.659 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:50.677 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:03:55.693 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:00.702 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:05.714 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:10.722 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:15.719 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:20.726 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:25.741 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:30.757 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:53.046 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:04:58.052 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:05:03.064 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:05:08.078 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:05:13.085 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:05:18.104 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:06:39.807 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:06:44.814 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:06:49.832 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:06:54.842 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:06:59.851 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:07:04.863 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:07:09.863 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:29.405 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:34.419 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:39.434 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:44.455 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:49.465 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:54.477 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:11:59.495 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:04.504 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:09.511 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:14.541 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:19.552 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:24.564 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:29.585 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:34.595 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:12:39.606 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:13:32.746 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:13:37.758 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:13:42.772 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:21:36.915 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:21:41.933 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:21:46.952 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:21:51.961 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:21:56.982 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:22:01.996 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:22:07.022 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:22:12.039 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
21:22:17.058 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
