11:54:50.157 INFO  Trades received on timestamp: 1642848890097
11:54:51.604 INFO  Trades received on timestamp: 1642848891566
11:54:51.604 INFO  Trades received on timestamp: 1642848891566
11:54:51.604 INFO  Trades received on timestamp: 1642848891566
11:55:22.430 INFO  Trades received on timestamp: 1642848922293
11:55:31.448 INFO  Trades received on timestamp: 1642848931371
11:55:48.509 INFO  Trades received on timestamp: 1642848947432
11:55:52.142 INFO  Trades received on timestamp: 1642848952085
17:44:18.605 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:23.385 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:28.437 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:33.620 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:38.394 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:43.392 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:48.496 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:53.505 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:44:58.488 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:03.414 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:08.519 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:13.522 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:18.522 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:23.580 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:28.522 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:33.684 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:38.556 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:43.573 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:48.509 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:53.529 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:45:58.564 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:03.541 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:08.576 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:13.552 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:18.550 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:23.609 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:28.577 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:33.602 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:38.578 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:43.709 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:48.655 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:53.632 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:46:58.641 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:03.629 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:08.634 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:13.654 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:18.673 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:23.726 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:28.749 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:33.812 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:38.704 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:43.689 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:48.720 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:53.706 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:47:58.725 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:03.758 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:08.796 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:13.759 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:18.750 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:23.762 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:28.742 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:33.790 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
17:48:38.755 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln'] 
18:24:12.890 INFO  Trades received on timestamp: 1642872255276
18:24:12.890 INFO  Trades received on timestamp: 1642872255276
18:24:13.188 INFO  Trades received on timestamp: 1642872255492
18:24:13.924 INFO  Trades received on timestamp: 1642872256292
18:24:52.790 INFO  Trades received on timestamp: 1642872295080
18:24:59.915 INFO  Trades received on timestamp: 1642872302284
18:25:07.740 INFO  Trades received on timestamp: 1642872309618
18:25:07.740 INFO  Trades received on timestamp: 1642872309618
18:25:14.801 INFO  Trades received on timestamp: 1642872317126
18:25:14.801 INFO  Trades received on timestamp: 1642872317126
18:25:34.116 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:25:41.090 INFO  Trades received on timestamp: 1642872343410
18:25:43.796 INFO  Trades received on timestamp: 1642872345625
18:25:43.796 INFO  Trades received on timestamp: 1642872345625
18:25:58.544 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:25:59.658 INFO  Trades received on timestamp: 1642872361958
18:26:00.988 INFO  Trades received on timestamp: 1642872363310
18:26:09.335 INFO  Trades received on timestamp: 1642872371239
18:26:35.921 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:27:12.150 INFO  Trades received on timestamp: 1642872434451
18:27:24.637 INFO  Trades received on timestamp: 1642872446994
18:27:34.369 INFO  Trades received on timestamp: 1642872456672
18:27:44.674 INFO  Trades received on timestamp: 1642872467052
18:27:52.739 INFO  Trades received on timestamp: 1642872475053
18:27:59.624 INFO  Trades received on timestamp: 1642872482002
18:28:08.438 INFO  Trades received on timestamp: 1642872490823
18:28:08.438 INFO  Trades received on timestamp: 1642872490823
18:28:11.872 INFO  Trades received on timestamp: 1642872494306
18:28:14.389 INFO  Trades received on timestamp: 1642872496723
18:28:14.389 INFO  Trades received on timestamp: 1642872496723
18:28:14.389 INFO  Trades received on timestamp: 1642872496723
18:28:16.361 INFO  Trades received on timestamp: 1642872498699
18:28:21.531 INFO  Trades received on timestamp: 1642872503796
18:28:47.045 INFO  Trades received on timestamp: 1642872529339
18:28:59.375 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:11.059 INFO  Trades received on timestamp: 1642872553294
18:29:21.553 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.553 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.553 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.553 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.568 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.568 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:21.568 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:29:31.366 INFO  Trades received on timestamp: 1642872573684
18:29:31.366 INFO  Trades received on timestamp: 1642872573684
18:30:06.621 INFO  Trades received on timestamp: 1642872608685
18:30:06.621 INFO  Trades received on timestamp: 1642872608685
18:30:06.621 INFO  Trades received on timestamp: 1642872608685
18:30:36.613 INFO  Trades received on timestamp: 1642872638878
18:30:39.702 INFO  Trades received on timestamp: 1642872642057
18:30:39.718 INFO  Trades received on timestamp: 1642872642057
18:30:39.718 INFO  Trades received on timestamp: 1642872642057
18:30:39.733 INFO  Trades received on timestamp: 1642872642057
18:31:05.253 INFO  Trades received on timestamp: 1642872667541
18:31:13.920 INFO  Trades received on timestamp: 1642872676210
18:31:39.178 INFO  Trades received on timestamp: 1642872701004
18:31:53.753 INFO  Trades received on timestamp: 1642872716054
18:32:31.411 INFO  Trades received on timestamp: 1642872753700
18:32:35.296 INFO  Trades received on timestamp: 1642872757653
18:33:05.792 INFO  Trades received on timestamp: 1642872787313
18:33:05.792 INFO  Trades received on timestamp: 1642872787313
18:33:06.925 INFO  Trades received on timestamp: 1642872789215
18:33:17.764 INFO  Trades received on timestamp: 1642872800107
18:33:17.764 INFO  Trades received on timestamp: 1642872800107
18:33:27.290 INFO  Trades received on timestamp: 1642872809665
18:33:38.298 INFO  Trades received on timestamp: 1642872820625
18:33:48.467 INFO  Trades received on timestamp: 1642872830753
18:33:59.636 INFO  Trades received on timestamp: 1642872841911
18:34:11.655 INFO  Trades received on timestamp: 1642872853967
18:34:24.198 INFO  Trades received on timestamp: 1642872866530
18:34:26.526 INFO  Trades received on timestamp: 1642872868625
18:34:26.526 INFO  Trades received on timestamp: 1642872868625
18:34:48.652 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:34:50.387 INFO  Trades received on timestamp: 1642872892690
18:34:53.683 INFO  Trades received on timestamp: 1642872896004
18:36:21.745 INFO  Trades received on timestamp: 1642872984072
18:36:21.745 INFO  Trades received on timestamp: 1642872984072
18:36:21.745 INFO  Trades received on timestamp: 1642872984072
18:36:22.608 INFO  Trades received on timestamp: 1642872984958
18:37:29.275 INFO  Trades received on timestamp: 1642873051186
18:37:39.100 INFO  Trades received on timestamp: 1642873061464
18:37:39.898 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:37:52.501 INFO  Trades received on timestamp: 1642873074876
18:37:52.501 INFO  Trades received on timestamp: 1642873074876
18:37:53.494 INFO  Trades received on timestamp: 1642873075883
18:37:53.494 INFO  Trades received on timestamp: 1642873075883
18:38:07.478 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:38:24.307 INFO  Trades received on timestamp: 1642873106656
18:38:36.883 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:38:47.846 INFO  Trades received on timestamp: 1642873130141
18:38:47.846 INFO  Trades received on timestamp: 1642873130141
18:39:22.033 INFO  Trades received on timestamp: 1642873164374
18:39:35.893 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:39:44.253 INFO  Trades received on timestamp: 1642873186515
18:39:47.272 INFO  Trades received on timestamp: 1642873189605
18:39:48.563 INFO  Trades received on timestamp: 1642873190885
18:39:50.392 INFO  Trades received on timestamp: 1642873192692
18:39:51.551 INFO  Trades received on timestamp: 1642873193921
18:39:53.345 INFO  Trades received on timestamp: 1642873195216
18:39:54.318 INFO  Trades received on timestamp: 1642873196653
18:39:55.170 INFO  Trades received on timestamp: 1642873197476
18:39:55.699 INFO  Trades received on timestamp: 1642873197997
18:39:57.391 INFO  Trades received on timestamp: 1642873199272
18:39:58.297 INFO  Trades received on timestamp: 1642873200626
18:39:59.691 INFO  Trades received on timestamp: 1642873202046
18:40:01.417 INFO  Trades received on timestamp: 1642873203709
18:40:02.672 INFO  Trades received on timestamp: 1642873205021
18:40:03.696 INFO  Trades received on timestamp: 1642873205972
18:40:04.016 INFO  Trades received on timestamp: 1642873206356
18:40:07.013 INFO  Trades received on timestamp: 1642873208805
18:40:07.313 INFO  Trades received on timestamp: 1642873207745
18:40:07.313 INFO  Trades received on timestamp: 1642873208210
18:40:07.953 INFO  Trades received on timestamp: 1642873210173
18:40:09.441 INFO  Trades received on timestamp: 1642873209056
18:40:09.441 INFO  Trades received on timestamp: 1642873209056
18:40:09.441 INFO  Trades received on timestamp: 1642873209078
18:40:09.441 INFO  Trades received on timestamp: 1642873209373
18:40:09.441 INFO  Trades received on timestamp: 1642873210343
18:40:09.441 INFO  Trades received on timestamp: 1642873210579
18:40:09.441 INFO  Trades received on timestamp: 1642873211563
18:40:09.606 INFO  Trades received on timestamp: 1642873211373
18:40:09.732 INFO  Trades received on timestamp: 1642873211965
18:40:11.039 INFO  Trades received on timestamp: 1642873213068
18:40:11.934 INFO  Trades received on timestamp: 1642873214288
18:40:13.304 INFO  Trades received on timestamp: 1642873215600
18:40:18.421 INFO  Trades received on timestamp: 1642873220762
18:40:19.827 INFO  Trades received on timestamp: 1642873222181
18:40:21.566 INFO  Trades received on timestamp: 1642873223360
18:40:22.552 INFO  Trades received on timestamp: 1642873224784
18:40:23.666 INFO  Trades received on timestamp: 1642873226045
18:40:23.666 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:40:24.906 INFO  Trades received on timestamp: 1642873227285
18:40:28.018 INFO  Trades received on timestamp: 1642873230333
18:40:29.503 INFO  Trades received on timestamp: 1642873231849
18:40:30.804 INFO  Trades received on timestamp: 1642873233187
18:40:31.549 INFO  Trades received on timestamp: 1642873233249
18:40:55.637 INFO  Trades received on timestamp: 1642873257968
18:41:04.692 INFO  Trades received on timestamp: 1642873266975
18:41:05.282 INFO  Trades received on timestamp: 1642873267554
18:41:07.023 INFO  Trades received on timestamp: 1642873269216
18:41:15.633 INFO  Trades received on timestamp: 1642873277864
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.149 INFO  Trades received on timestamp: 1642873299475
18:41:37.165 INFO  Trades received on timestamp: 1642873299475
18:41:43.257 INFO  Trades received on timestamp: 1642873305584
18:41:57.401 INFO  Trades received on timestamp: 1642873319739
18:42:10.069 INFO  Trades received on timestamp: 1642873332346
18:42:17.440 INFO  Trades received on timestamp: 1642873339803
18:42:17.702 INFO  Trades received on timestamp: 1642873340092
18:42:21.570 INFO  Trades received on timestamp: 1642873343922
18:42:22.036 INFO  Trades received on timestamp: 1642873344379
18:42:22.036 INFO  Trades received on timestamp: 1642873344379
18:42:31.831 INFO  Trades received on timestamp: 1642873354210
18:42:37.728 INFO  Trades received on timestamp: 1642873360027
18:42:40.040 INFO  Trades received on timestamp: 1642873362396
18:42:54.784 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:43:06.131 INFO  Trades received on timestamp: 1642873388372
18:43:14.364 INFO  Trades received on timestamp: 1642873396673
18:43:15.634 INFO  Trades received on timestamp: 1642873398021
18:43:15.634 INFO  Trades received on timestamp: 1642873398021
18:43:18.132 INFO  Trades received on timestamp: 1642873400504
18:43:26.779 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:43:26.810 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:44:01.022 INFO  Trades received on timestamp: 1642873443291
18:44:04.633 INFO  Trades received on timestamp: 1642873446835
18:44:24.410 INFO  Trades received on timestamp: 1642873466745
18:44:24.410 INFO  Trades received on timestamp: 1642873466745
18:44:25.178 INFO  Trades received on timestamp: 1642873467523
18:44:26.035 INFO  Trades received on timestamp: 1642873467675
18:44:27.761 INFO  Trades received on timestamp: 1642873469713
18:44:29.383 INFO  Trades received on timestamp: 1642873471681
18:44:31.087 INFO  Trades received on timestamp: 1642873473394
18:44:36.875 INFO  Trades received on timestamp: 1642873479189
18:44:43.410 INFO  Trades received on timestamp: 1642873485716
18:44:44.070 INFO  Trades received on timestamp: 1642873486355
18:44:45.748 INFO  Trades received on timestamp: 1642873488098
18:44:58.826 INFO  Trades received on timestamp: 1642873501172
18:44:58.826 INFO  Trades received on timestamp: 1642873501172
18:45:00.495 INFO  Trades received on timestamp: 1642873502820
18:45:20.019 INFO  Trades received on timestamp: 1642873522328
18:45:21.363 INFO  Trades received on timestamp: 1642873523688
18:45:21.363 INFO  Trades received on timestamp: 1642873523688
18:45:21.363 INFO  Trades received on timestamp: 1642873523688
18:45:21.554 INFO  Trades received on timestamp: 1642873523874
18:45:21.554 INFO  Trades received on timestamp: 1642873523874
18:45:32.127 INFO  Trades received on timestamp: 1642873534493
18:46:42.271 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:47:31.762 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:47:45.533 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:47:46.335 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:47:48.256 INFO  Trades received on timestamp: 1642873670549
18:48:18.916 INFO  Trades received on timestamp: 1642873701243
18:48:23.120 INFO  Trades received on timestamp: 1642873705463
18:48:52.348 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:49:02.566 INFO  Trades received on timestamp: 1642873730634
18:50:09.669 INFO  Trades received on timestamp: 1642873811959
18:50:50.094 INFO  Trades received on timestamp: 1642873852369
18:50:55.744 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:51:25.498 INFO  Trades received on timestamp: 1642873887861
18:51:25.498 INFO  Trades received on timestamp: 1642873887861
18:51:31.948 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:51:31.964 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:51:32.168 INFO  Trades received on timestamp: 1642873894489
18:51:47.374 INFO  Trades received on timestamp: 1642873909619
18:51:55.934 INFO  Trades received on timestamp: 1642873918269
18:52:00.822 INFO  Trades received on timestamp: 1642873923106
18:52:44.437 INFO  Trades received on timestamp: 1642873966791
18:52:47.537 INFO  Trades received on timestamp: 1642873969803
18:53:02.498 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:53:05.665 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:53:15.288 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:53:39.278 INFO  Trades received on timestamp: 1642874021561
18:53:44.842 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:53:44.842 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:54:33.365 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:54:33.373 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:54:40.477 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:55:13.531 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:55:13.531 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:55:19.848 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:55:19.864 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:55:22.098 INFO  Trades received on timestamp: 1642874124418
18:55:25.822 INFO  Trades received on timestamp: 1642874128196
18:55:50.295 INFO  Trades received on timestamp: 1642874152666
18:55:59.014 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:56:00.665 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:56:02.408 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:56:03.689 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:56:03.705 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:56:11.930 INFO  Trades received on timestamp: 1642874174275
18:56:11.930 INFO  Trades received on timestamp: 1642874174275
18:56:11.930 INFO  Trades received on timestamp: 1642874174275
18:56:25.525 INFO  Trades received on timestamp: 1642874187806
18:56:36.238 INFO  Trades received on timestamp: 1642874198569
18:56:45.369 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

18:57:25.201 INFO  Trades received on timestamp: 1642874247500
18:57:25.201 INFO  Trades received on timestamp: 1642874247500
18:57:34.032 INFO  Trades received on timestamp: 1642874256339
18:57:42.371 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:57:50.377 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

18:59:30.099 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

18:59:30.115 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:00:08.056 INFO  Trades received on timestamp: 1642874410388
19:00:08.056 INFO  Trades received on timestamp: 1642874410388
19:00:12.331 INFO  Trades received on timestamp: 1642874414623
19:00:16.547 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:00:23.481 INFO  Trades received on timestamp: 1642874425787
19:00:23.481 INFO  Trades received on timestamp: 1642874425787
19:00:30.394 INFO  Trades received on timestamp: 1642874432726
19:00:30.394 INFO  Trades received on timestamp: 1642874432726
19:00:52.632 INFO  Trades received on timestamp: 1642874455026
19:00:52.632 INFO  Trades received on timestamp: 1642874455026
19:00:52.632 INFO  Trades received on timestamp: 1642874455026
19:00:52.632 INFO  Trades received on timestamp: 1642874455026
19:01:00.148 INFO  Trades received on timestamp: 1642874462509
19:01:31.615 INFO  Trades received on timestamp: 1642874493969
19:01:31.615 INFO  Trades received on timestamp: 1642874493969
19:01:31.615 INFO  Trades received on timestamp: 1642874493969
19:01:31.615 INFO  Trades received on timestamp: 1642874493969
19:01:31.615 INFO  Trades received on timestamp: 1642874493969
19:01:31.623 INFO  Trades received on timestamp: 1642874493969
19:01:31.623 INFO  Trades received on timestamp: 1642874493969
19:01:31.623 INFO  Trades received on timestamp: 1642874493969
19:01:31.623 INFO  Trades received on timestamp: 1642874493969
19:01:31.631 INFO  Trades received on timestamp: 1642874493969
19:01:31.631 INFO  Trades received on timestamp: 1642874493969
19:01:31.639 INFO  Trades received on timestamp: 1642874493969
19:01:31.639 INFO  Trades received on timestamp: 1642874493969
19:01:43.192 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:01:43.192 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:01:43.192 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:51.991 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.006 INFO  Trades received on timestamp: 1642874514234
19:01:52.022 INFO  Trades received on timestamp: 1642874514234
19:01:52.022 INFO  Trades received on timestamp: 1642874514234
19:01:52.038 INFO  Trades received on timestamp: 1642874514234
19:01:52.053 INFO  Trades received on timestamp: 1642874514234
19:01:52.053 INFO  Trades received on timestamp: 1642874514234
19:01:57.686 INFO  Trades received on timestamp: 1642874519985
19:01:57.829 INFO  Trades received on timestamp: 1642874520192
19:02:04.817 INFO  Trades received on timestamp: 1642874527073
19:02:06.245 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:02:07.428 INFO  Trades received on timestamp: 1642874529772
19:02:07.428 INFO  Trades received on timestamp: 1642874529772
19:02:10.523 INFO  Trades received on timestamp: 1642874532836
19:02:10.601 INFO  Trades received on timestamp: 1642874532998
19:02:10.742 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:02:11.721 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:02:11.721 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:02:33.508 INFO  Trades received on timestamp: 1642874555767
19:02:33.540 INFO  Trades received on timestamp: 1642874555767
19:02:33.548 INFO  Trades received on timestamp: 1642874555767
19:02:33.548 INFO  Trades received on timestamp: 1642874555767
19:02:33.548 INFO  Trades received on timestamp: 1642874555767
19:02:33.548 INFO  Trades received on timestamp: 1642874555767
19:02:33.548 INFO  Trades received on timestamp: 1642874555767
19:02:33.556 INFO  Trades received on timestamp: 1642874555767
19:02:33.556 INFO  Trades received on timestamp: 1642874555767
19:02:34.117 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:02:49.638 INFO  Trades received on timestamp: 1642874571971
19:02:51.071 INFO  Trades received on timestamp: 1642874573478
19:02:51.843 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:03:06.395 INFO  Trades received on timestamp: 1642874588261
19:03:08.133 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:03:17.598 INFO  Trades received on timestamp: 1642874599976
19:03:18.381 INFO  Trades received on timestamp: 1642874600766
19:03:22.077 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:03:22.767 INFO  Trades received on timestamp: 1642874605159
19:03:29.078 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:03:37.688 INFO  Trades received on timestamp: 1642874619981
19:03:40.876 INFO  Trades received on timestamp: 1642874623260
19:03:41.243 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:03:41.719 INFO  Trades received on timestamp: 1642874624125
19:03:46.462 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:03:46.462 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:03:46.462 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:04:23.210 INFO  Trades received on timestamp: 1642874665532
19:04:23.210 INFO  Trades received on timestamp: 1642874665532
19:04:27.984 INFO  Trades received on timestamp: 1642874670317
19:04:27.984 INFO  Trades received on timestamp: 1642874670317
19:04:34.666 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:34.713 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.150 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.150 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.150 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.150 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.150 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.166 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:37.166 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:04:52.428 INFO  Trades received on timestamp: 1642874694774
19:05:00.725 INFO  Trades received on timestamp: 1642874703118
19:05:28.305 INFO  Trades received on timestamp: 1642874730390
19:05:28.305 INFO  Trades received on timestamp: 1642874730390
19:05:28.479 INFO  Trades received on timestamp: 1642874730834
19:05:29.818 INFO  Trades received on timestamp: 1642874732220
19:05:53.352 INFO  Trades received on timestamp: 1642874755774
19:06:09.682 INFO  Trades received on timestamp: 1642874772060
19:06:18.075 INFO  Trades received on timestamp: 1642874780348
19:06:33.817 INFO  Trades received on timestamp: 1642874796131
19:06:48.608 INFO  Trades received on timestamp: 1642874810865
19:06:49.876 INFO  Trades received on timestamp: 1642874812229
19:06:51.360 INFO  Trades received on timestamp: 1642874813691
19:07:01.626 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:07:01.642 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:07:05.488 INFO  Trades received on timestamp: 1642874827834
19:07:05.708 INFO  Trades received on timestamp: 1642874827997
19:07:05.857 INFO  Trades received on timestamp: 1642874828206
19:07:07.019 INFO  Trades received on timestamp: 1642874829385
19:07:07.714 INFO  Trades received on timestamp: 1642874830122
19:07:08.412 INFO  Trades received on timestamp: 1642874830776
19:07:09.946 INFO  Trades received on timestamp: 1642874832330
19:07:11.106 INFO  Trades received on timestamp: 1642874833517
19:07:13.292 INFO  Trades received on timestamp: 1642874835683
19:07:17.127 INFO  Trades received on timestamp: 1642874839501
19:07:18.533 INFO  Trades received on timestamp: 1642874840865
19:07:19.396 INFO  Trades received on timestamp: 1642874841736
19:07:19.396 INFO  Trades received on timestamp: 1642874841736
19:07:20.525 INFO  Trades received on timestamp: 1642874842506
19:07:21.474 INFO  Trades received on timestamp: 1642874843831
19:07:22.818 INFO  Trades received on timestamp: 1642874845195
19:07:40.909 INFO  Trades received on timestamp: 1642874862770
19:07:42.843 INFO  Trades received on timestamp: 1642874865223
19:07:48.070 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:07:52.355 INFO  Trades received on timestamp: 1642874874734
19:07:59.049 INFO  Trades received on timestamp: 1642874881405
19:08:19.299 INFO  Trades received on timestamp: 1642874901540
19:08:19.347 INFO  Trades received on timestamp: 1642874901540
19:08:21.688 INFO  Trades received on timestamp: 1642874903994
19:08:21.688 INFO  Trades received on timestamp: 1642874903994
19:08:21.688 INFO  Trades received on timestamp: 1642874903994
19:08:21.688 INFO  Trades received on timestamp: 1642874903994
19:08:23.735 INFO  Trades received on timestamp: 1642874906033
19:08:23.735 INFO  Trades received on timestamp: 1642874906033
19:08:24.368 INFO  Trades received on timestamp: 1642874906660
19:08:24.890 INFO  Trades received on timestamp: 1642874907165
19:08:32.290 INFO  Trades received on timestamp: 1642874914653
19:08:32.290 INFO  Trades received on timestamp: 1642874914653
19:08:35.567 INFO  Trades received on timestamp: 1642874917986
19:08:42.715 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:08:54.676 INFO  Trades received on timestamp: 1642874937007
19:08:54.989 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:08:54.989 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:09:04.099 INFO  Trades received on timestamp: 1642874946466
19:09:09.441 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:09:09.706 INFO  Trades received on timestamp: 1642874952076
19:09:16.075 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:09:16.075 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:09:22.486 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:09:30.911 INFO  Trades received on timestamp: 1642874973267
19:10:08.646 INFO  Trades received on timestamp: 1642875010993
19:10:08.646 INFO  Trades received on timestamp: 1642875010993
19:10:15.528 INFO  Trades received on timestamp: 1642875017764
19:10:33.750 INFO  Trades received on timestamp: 1642875036138
19:10:45.032 INFO  Trades received on timestamp: 1642875047378
19:10:53.910 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:11:21.025 INFO  Trades received on timestamp: 1642875083346
19:11:31.768 INFO  Trades received on timestamp: 1642875094172
19:11:31.768 INFO  Trades received on timestamp: 1642875094172
19:11:31.768 INFO  Trades received on timestamp: 1642875094172
19:11:31.784 INFO  Trades received on timestamp: 1642875094172
19:11:50.364 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:12:03.368 INFO  Trades received on timestamp: 1642875125480
19:12:17.162 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:12:54.727 INFO  Trades received on timestamp: 1642875177181
19:12:59.571 INFO  Trades received on timestamp: 1642875181955
19:13:06.810 INFO  Trades received on timestamp: 1642875189193
19:13:50.688 INFO  Trades received on timestamp: 1642875232982
19:14:17.338 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:14:18.756 INFO  Trades received on timestamp: 1642875261060
19:14:37.176 INFO  Trades received on timestamp: 1642875279558
19:14:45.923 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:14.750 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.265 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.265 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.312 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.593 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.922 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:15.994 INFO  Trades received on timestamp: 1642875318359
19:15:15.994 INFO  Trades received on timestamp: 1642875318359
19:15:20.854 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:24.165 INFO  Trades received on timestamp: 1642875326494
19:15:31.223 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:15:57.464 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:16:12.066 INFO  Trades received on timestamp: 1642875374453
19:16:23.981 INFO  Trades received on timestamp: 1642875386293
19:16:37.689 INFO  Trades received on timestamp: 1642875399970
19:16:42.278 INFO  Trades received on timestamp: 1642875404621
19:17:05.828 INFO  Trades received on timestamp: 1642875428149
19:17:05.828 INFO  Trades received on timestamp: 1642875428149
19:17:08.574 INFO  Trades received on timestamp: 1642875430445
19:17:39.257 INFO  Trades received on timestamp: 1642875461609
19:17:55.540 INFO  Trades received on timestamp: 1642875477925
19:18:01.658 INFO  Trades received on timestamp: 1642875483973
19:18:01.658 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.855 INFO  Trades received on timestamp: 1642875483973
19:18:01.871 INFO  Trades received on timestamp: 1642875484253
19:18:01.933 INFO  Trades received on timestamp: 1642875484253
19:18:03.136 INFO  Trades received on timestamp: 1642875485495
19:18:04.310 INFO  Trades received on timestamp: 1642875486677
19:18:05.102 INFO  Trades received on timestamp: 1642875487493
19:18:37.186 INFO  Trades received on timestamp: 1642875519576
19:18:37.201 INFO  Trades received on timestamp: 1642875519576
19:18:52.484 INFO  Trades received on timestamp: 1642875534735
19:18:58.032 INFO  Trades received on timestamp: 1642875540310
19:18:58.032 INFO  Trades received on timestamp: 1642875540310
19:19:22.834 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:19:22.850 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:19:22.850 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:19:22.850 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:19:42.927 INFO  Trades received on timestamp: 1642875585311
19:19:44.465 INFO  Trades received on timestamp: 1642875586770
19:19:46.441 INFO  Trades received on timestamp: 1642875588072
19:19:46.966 INFO  Trades received on timestamp: 1642875589372
19:19:48.395 INFO  Trades received on timestamp: 1642875590728
19:19:49.589 INFO  Trades received on timestamp: 1642875592015
19:19:50.869 INFO  Trades received on timestamp: 1642875593279
19:20:04.659 INFO  Trades received on timestamp: 1642875607019
19:20:04.659 INFO  Trades received on timestamp: 1642875607019
19:20:09.552 INFO  Trades received on timestamp: 1642875611872
19:20:10.692 INFO  Trades received on timestamp: 1642875613111
19:20:12.459 INFO  Trades received on timestamp: 1642875614482
19:20:13.313 INFO  Trades received on timestamp: 1642875615698
19:20:14.498 INFO  Trades received on timestamp: 1642875616891
19:20:15.891 INFO  Trades received on timestamp: 1642875618284
19:20:52.670 INFO  Trades received on timestamp: 1642875655063
19:21:01.173 INFO  Trades received on timestamp: 1642875663474
19:21:12.907 INFO  Trades received on timestamp: 1642875675254
19:21:13.162 INFO  Trades received on timestamp: 1642875675478
19:21:14.107 INFO  Trades received on timestamp: 1642875676498
19:21:14.367 INFO  Trades received on timestamp: 1642875676712
19:21:15.612 INFO  Trades received on timestamp: 1642875678003
19:21:16.857 INFO  Trades received on timestamp: 1642875679186
19:21:18.251 INFO  Trades received on timestamp: 1642875680530
19:21:19.535 INFO  Trades received on timestamp: 1642875681890
19:21:20.817 INFO  Trades received on timestamp: 1642875683139
19:21:22.329 INFO  Trades received on timestamp: 1642875684687
19:21:24.038 INFO  Trades received on timestamp: 1642875686378
19:21:26.059 INFO  Trades received on timestamp: 1642875688387
19:21:27.184 INFO  Trades received on timestamp: 1642875689553
19:21:30.550 INFO  Trades received on timestamp: 1642875692799
19:21:31.883 INFO  Trades received on timestamp: 1642875694181
19:21:31.883 INFO  Trades received on timestamp: 1642875694181
19:21:37.156 INFO  Trades received on timestamp: 1642875699469
19:21:45.110 INFO  Trades received on timestamp: 1642875707334
19:21:48.745 INFO  Trades received on timestamp: 1642875711106
19:21:50.139 INFO  Trades received on timestamp: 1642875712482
19:22:10.391 INFO  Trades received on timestamp: 1642875732721
19:22:12.990 INFO  Trades received on timestamp: 1642875735283
19:22:13.960 INFO  Trades received on timestamp: 1642875736238
19:22:14.127 INFO  Trades received on timestamp: 1642875736492
19:22:26.588 INFO  Trades received on timestamp: 1642875748952
19:22:26.596 INFO  Trades received on timestamp: 1642875748952
19:23:07.414 INFO  Trades received on timestamp: 1642875789736
19:23:25.023 INFO  Trades received on timestamp: 1642875807291
19:24:13.144 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:24:22.698 INFO  Trades received on timestamp: 1642875865093
19:24:22.698 INFO  Trades received on timestamp: 1642875865093
19:25:41.366 INFO  Trades received on timestamp: 1642875943706
19:25:45.927 INFO  Trades received on timestamp: 1642875948221
19:26:13.719 INFO  Trades received on timestamp: 1642875976066
19:26:14.263 INFO  Trades received on timestamp: 1642875976640
19:26:14.263 INFO  Trades received on timestamp: 1642875976640
19:26:14.263 INFO  Trades received on timestamp: 1642875976640
19:26:32.215 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:26:40.088 INFO  Trades received on timestamp: 1642876002440
19:26:40.088 INFO  Trades received on timestamp: 1642876002440
19:26:40.839 INFO  Trades received on timestamp: 1642876003106
19:26:42.039 INFO  Trades received on timestamp: 1642876004243
19:26:58.759 INFO  Trades received on timestamp: 1642876021105
19:27:27.719 INFO  Trades received on timestamp: 1642876049639
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.552 INFO  Trades received on timestamp: 1642876059879
19:27:37.568 INFO  Trades received on timestamp: 1642876059879
19:27:46.308 INFO  Trades received on timestamp: 1642876068649
19:27:46.308 INFO  Trades received on timestamp: 1642876068649
19:27:50.989 INFO  Trades received on timestamp: 1642876073378
19:27:54.839 INFO  Trades received on timestamp: 1642876077072
19:28:05.582 INFO  Trades received on timestamp: 1642876087899
19:28:13.491 INFO  Trades received on timestamp: 1642876095754
19:28:27.468 INFO  Trades received on timestamp: 1642876109805
19:28:43.969 INFO  Trades received on timestamp: 1642876126296
19:28:45.131 INFO  Trades received on timestamp: 1642876127508
19:28:45.131 INFO  Trades received on timestamp: 1642876127508
19:28:45.140 INFO  Trades received on timestamp: 1642876127508
19:28:45.678 INFO  Trades received on timestamp: 1642876128056
19:28:48.312 INFO  Trades received on timestamp: 1642876130665
19:28:57.694 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:30:11.546 INFO  Trades received on timestamp: 1642876213886
19:30:19.946 INFO  Trades received on timestamp: 1642876222272
19:30:19.946 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:30:20.311 INFO  Trades received on timestamp: 1642876222638
19:30:22.773 INFO  Trades received on timestamp: 1642876225115
19:30:22.773 INFO  Trades received on timestamp: 1642876225115
19:30:22.781 INFO  Trades received on timestamp: 1642876225115
19:30:38.451 INFO  Trades received on timestamp: 1642876240848
19:31:04.734 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:31:04.855 INFO  Trades received on timestamp: 1642876267152
19:31:14.394 INFO  Trades received on timestamp: 1642876276771
19:31:14.394 INFO  Trades received on timestamp: 1642876276771
19:31:15.667 INFO  Trades received on timestamp: 1642876278118
19:31:17.619 INFO  Trades received on timestamp: 1642876280045
19:31:17.619 INFO  Trades received on timestamp: 1642876280045
19:31:19.161 INFO  Trades received on timestamp: 1642876281593
19:31:20.544 INFO  Trades received on timestamp: 1642876282883
19:31:22.962 INFO  Trades received on timestamp: 1642876285382
19:31:29.251 INFO  Trades received on timestamp: 1642876291627
19:32:10.569 INFO  Trades received on timestamp: 1642876332974
19:32:13.644 INFO  Trades received on timestamp: 1642876336074
19:33:31.273 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:33:47.170 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:34:33.620 INFO  Trades received on timestamp: 1642876476026
19:34:33.636 INFO  Trades received on timestamp: 1642876476026
19:34:42.637 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:34:46.641 INFO  Trades received on timestamp: 1642876488887
19:35:29.849 INFO  Trades received on timestamp: 1642876532203
19:35:29.849 INFO  Trades received on timestamp: 1642876532203
19:35:34.325 INFO  Trades received on timestamp: 1642876536651
19:35:58.795 INFO  Trades received on timestamp: 1642876560985
19:35:58.795 INFO  Trades received on timestamp: 1642876560985
19:36:33.312 INFO  Trades received on timestamp: 1642876595660
19:36:39.743 INFO  Trades received on timestamp: 1642876601872
19:36:48.345 INFO  Trades received on timestamp: 1642876610675
19:36:59.489 INFO  Trades received on timestamp: 1642876621759
19:36:59.489 INFO  Trades received on timestamp: 1642876621759
19:36:59.489 INFO  Trades received on timestamp: 1642876621759
19:37:03.694 INFO  Trades received on timestamp: 1642876626055
19:37:26.688 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:37:34.198 INFO  Trades received on timestamp: 1642876656520
19:37:34.198 INFO  Trades received on timestamp: 1642876656520
19:37:34.198 INFO  Trades received on timestamp: 1642876656520
19:37:34.198 INFO  Trades received on timestamp: 1642876656520
19:37:34.198 INFO  Trades received on timestamp: 1642876656520
19:38:52.105 INFO  Trades received on timestamp: 1642876734465
19:38:53.105 INFO  Trades received on timestamp: 1642876735466
19:38:53.105 INFO  Trades received on timestamp: 1642876735466
19:38:53.105 INFO  Trades received on timestamp: 1642876735466
19:38:54.314 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:39:00.028 INFO  Trades received on timestamp: 1642876742378
19:39:00.028 INFO  Trades received on timestamp: 1642876742378
19:39:00.957 INFO  Trades received on timestamp: 1642876743163
19:39:00.957 INFO  Trades received on timestamp: 1642876743163
19:39:00.957 INFO  Trades received on timestamp: 1642876743163
19:39:00.957 INFO  Trades received on timestamp: 1642876743163
19:39:11.027 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:39:11.027 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:39:22.137 INFO  Trades received on timestamp: 1642876764454
19:39:30.880 INFO  Trades received on timestamp: 1642876773180
19:39:31.772 INFO  Trades received on timestamp: 1642876774117
19:39:38.698 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:39:39.280 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:39:40.625 INFO  Trades received on timestamp: 1642876783021
19:39:41.023 INFO  Trades received on timestamp: 1642876783387
19:39:55.607 INFO  Trades received on timestamp: 1642876797964
19:39:59.162 INFO  Trades received on timestamp: 1642876801578
19:40:26.319 INFO  Trades received on timestamp: 1642876828646
19:40:36.168 INFO  Trades received on timestamp: 1642876838453
19:40:42.175 INFO  Trades received on timestamp: 1642876844549
19:40:52.532 INFO  Trades received on timestamp: 1642876854892
19:41:04.914 INFO  Trades received on timestamp: 1642876867199
19:41:04.914 INFO  Trades received on timestamp: 1642876867199
19:41:24.387 INFO  Trades received on timestamp: 1642876886711
19:41:24.387 INFO  Trades received on timestamp: 1642876886711
19:41:32.828 INFO  Trades received on timestamp: 1642876895162
19:42:21.170 INFO  Trades received on timestamp: 1642876943524
19:42:21.170 INFO  Trades received on timestamp: 1642876943524
19:42:23.571 INFO  Trades received on timestamp: 1642876945938
19:42:23.571 INFO  Trades received on timestamp: 1642876945938
19:42:23.726 INFO  Trades received on timestamp: 1642876946089
19:42:27.536 INFO  Trades received on timestamp: 1642876949866
19:42:27.536 INFO  Trades received on timestamp: 1642876949866
19:42:27.536 INFO  Trades received on timestamp: 1642876949866
19:42:27.614 INFO  Trades received on timestamp: 1642876949960
19:42:27.614 INFO  Trades received on timestamp: 1642876949960
19:42:27.630 INFO  Trades received on timestamp: 1642876949960
19:42:47.256 INFO  Trades received on timestamp: 1642876969554
19:42:47.256 INFO  Trades received on timestamp: 1642876969554
19:42:50.531 INFO  Trades received on timestamp: 1642876972407
19:42:51.877 INFO  Trades received on timestamp: 1642876974236
19:43:04.875 INFO  Trades received on timestamp: 1642876987224
19:43:19.337 INFO  Trades received on timestamp: 1642877001728
19:43:19.984 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:43:24.972 INFO  Trades received on timestamp: 1642877007337
19:43:31.922 INFO  Trades received on timestamp: 1642877014335
19:43:40.714 INFO  Trades received on timestamp: 1642877023003
19:43:40.714 INFO  Trades received on timestamp: 1642877023003
19:43:41.427 INFO  Trades received on timestamp: 1642877023762
19:43:51.200 INFO  Trades received on timestamp: 1642877033541
19:43:51.200 INFO  Trades received on timestamp: 1642877033541
19:44:12.029 INFO  Trades received on timestamp: 1642877054450
19:44:21.416 INFO  Trades received on timestamp: 1642877063693
19:44:25.536 INFO  Trades received on timestamp: 1642877067846
19:44:25.536 INFO  Trades received on timestamp: 1642877067846
19:44:28.865 INFO  Trades received on timestamp: 1642877071226
19:44:35.003 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:44:35.544 INFO  Trades received on timestamp: 1642877077896
19:44:41.754 INFO  Trades received on timestamp: 1642877084049
19:44:52.025 INFO  Trades received on timestamp: 1642877094414
19:44:54.460 INFO  Trades received on timestamp: 1642877096840
19:44:54.460 INFO  Trades received on timestamp: 1642877096840
19:44:54.460 INFO  Trades received on timestamp: 1642877096840
19:44:54.460 INFO  Trades received on timestamp: 1642877096840
19:44:54.460 INFO  Trades received on timestamp: 1642877096840
19:44:54.468 INFO  Trades received on timestamp: 1642877096840
19:44:54.468 INFO  Trades received on timestamp: 1642877096840
19:44:54.484 INFO  Trades received on timestamp: 1642877096840
19:44:54.484 INFO  Trades received on timestamp: 1642877096840
19:44:54.484 INFO  Trades received on timestamp: 1642877096840
19:44:54.492 INFO  Trades received on timestamp: 1642877096840
19:44:54.492 INFO  Trades received on timestamp: 1642877096840
19:44:54.492 INFO  Trades received on timestamp: 1642877096840
19:44:54.492 INFO  Trades received on timestamp: 1642877096840
19:44:54.508 INFO  Trades received on timestamp: 1642877096840
19:44:54.508 INFO  Trades received on timestamp: 1642877096840
19:44:54.516 INFO  Trades received on timestamp: 1642877096840
19:44:54.524 INFO  Trades received on timestamp: 1642877096840
19:44:54.572 INFO  Trades received on timestamp: 1642877096840
19:44:54.572 INFO  Trades received on timestamp: 1642877096840
19:44:54.572 INFO  Trades received on timestamp: 1642877096840
19:44:54.580 INFO  Trades received on timestamp: 1642877096840
19:44:54.580 INFO  Trades received on timestamp: 1642877096840
19:44:54.580 INFO  Trades received on timestamp: 1642877096840
19:44:54.580 INFO  Trades received on timestamp: 1642877096840
19:44:54.580 INFO  Trades received on timestamp: 1642877096840
19:45:02.143 INFO  Trades received on timestamp: 1642877104460
19:45:02.334 INFO  Trades received on timestamp: 1642877104629
19:45:02.334 INFO  Trades received on timestamp: 1642877104629
19:45:14.391 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:45:14.391 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.625 INFO  Trades received on timestamp: 1642877129941
19:45:27.672 INFO  Trades received on timestamp: 1642877129941
19:45:27.672 INFO  Trades received on timestamp: 1642877129941
19:45:27.672 INFO  Trades received on timestamp: 1642877129941
19:45:27.672 INFO  Trades received on timestamp: 1642877129941
19:45:27.688 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:27.703 INFO  Trades received on timestamp: 1642877129941
19:45:41.115 INFO  Trades received on timestamp: 1642877143425
19:46:00.775 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:46:00.783 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:46:12.364 INFO  Trades received on timestamp: 1642877174758
19:46:33.351 INFO  Trades received on timestamp: 1642877195665
19:46:34.546 INFO  Trades received on timestamp: 1642877196856
19:46:34.546 INFO  Trades received on timestamp: 1642877196856
19:46:36.913 INFO  Trades received on timestamp: 1642877199263
19:46:54.782 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:47:00.153 INFO  Trades received on timestamp: 1642877222494
19:47:00.785 INFO  Trades received on timestamp: 1642877223070
19:47:06.976 INFO  Trades received on timestamp: 1642877229283
19:47:13.160 INFO  Trades received on timestamp: 1642877235473
19:47:18.751 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:47:18.751 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:47:18.759 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:47:18.759 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:47:24.295 INFO  Trades received on timestamp: 1642877246708
19:47:24.295 INFO  Trades received on timestamp: 1642877246708
19:47:33.213 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:47:33.213 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:47:33.213 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:47:33.403 INFO  Trades received on timestamp: 1642877255769
19:47:33.411 INFO  Trades received on timestamp: 1642877255769
19:47:33.467 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:47:33.546 INFO  Trades received on timestamp: 1642877255883
19:47:52.248 INFO  Trades received on timestamp: 1642877274584
19:48:13.024 INFO  Trades received on timestamp: 1642877295261
19:48:20.621 INFO  Trades received on timestamp: 1642877302963
19:48:24.376 INFO  Trades received on timestamp: 1642877306737
19:48:24.416 INFO  Trades received on timestamp: 1642877306805
19:48:24.416 INFO  Trades received on timestamp: 1642877306805
19:48:24.875 INFO  Trades received on timestamp: 1642877307257
19:48:25.070 INFO  Trades received on timestamp: 1642877307459
19:48:25.070 INFO  Trades received on timestamp: 1642877307482
19:48:25.357 INFO  Trades received on timestamp: 1642877307654
19:48:25.570 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:48:25.578 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:49:06.757 INFO  Trades received on timestamp: 1642877348611
19:49:41.898 INFO  Trades received on timestamp: 1642877384238
19:49:42.102 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:49:42.360 INFO  Trades received on timestamp: 1642877384670
19:50:21.237 INFO  Trades received on timestamp: 1642877423539
19:50:21.237 INFO  Trades received on timestamp: 1642877423539
19:50:22.815 INFO  Trades received on timestamp: 1642877425186
19:50:22.815 INFO  Trades received on timestamp: 1642877425186
19:50:24.826 ERROR   $$ relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.maticpln_trades" does not exist
LINE 1: INSERT INTO zonda.maticpln_trades (id, price, volume, "times...
                    ^

19:50:35.430 INFO  Trades received on timestamp: 1642877437766
19:50:49.158 ERROR   $$ relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.adapln_trades" does not exist
LINE 1: INSERT INTO zonda.adapln_trades (id, price, volume, "timesta...
                    ^

19:50:55.520 INFO  Trades received on timestamp: 1642877457861
19:50:56.088 INFO  Trades received on timestamp: 1642877458500
19:51:05.274 INFO  Trades received on timestamp: 1642877467624
19:51:13.494 INFO  Trades received on timestamp: 1642877475843
19:51:15.218 INFO  Trades received on timestamp: 1642877477625
19:51:46.724 INFO  Trades received on timestamp: 1642877509045
19:52:07.294 INFO  Trades received on timestamp: 1642877529633
19:52:07.294 INFO  Trades received on timestamp: 1642877529633
19:52:07.294 INFO  Trades received on timestamp: 1642877529633
19:52:07.294 INFO  Trades received on timestamp: 1642877529633
19:52:07.294 INFO  Trades received on timestamp: 1642877529687
19:52:24.771 INFO  Trades received on timestamp: 1642877547150
19:52:26.703 INFO  Trades received on timestamp: 1642877549104
19:52:26.703 INFO  Trades received on timestamp: 1642877549104
19:52:47.211 INFO  Trades received on timestamp: 1642877569560
19:52:47.211 INFO  Trades received on timestamp: 1642877569560
19:53:05.463 ERROR   $$ relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^
 $$ 
Traceback (most recent call last):
  File "C:/Users/oskar/Desktop/repo/db_ex_connections/zonda_trades.py", line 46, in single_wss_run
    cursor.execute(f"""INSERT INTO zonda.{symbol}_trades (id, price, volume, "timestamp")
psycopg2.errors.UndefinedTable: relation "zonda.xrppln_trades" does not exist
LINE 1: INSERT INTO zonda.xrppln_trades (id, price, volume, "timesta...
                    ^

19:10:06.795 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:11.381 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:16.392 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:21.410 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:26.379 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:31.397 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:36.398 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:41.390 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:46.573 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:51.596 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:10:56.438 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:01.432 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:07.023 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:11.471 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:16.457 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:21.496 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:26.486 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:31.465 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
19:11:36.655 INFO  Ob received and successfully saved into database for ['btcpln', 'ethpln', 'lunapln', 'ftmpln', 'btceur', 'xrppln', 'etheur', 'adapln', 'maticpln', 'usdtpln', 'dotpln', 'avaxpln', 'dogepln', 'trxpln', 'manapln', 'linkpln'] 
20:26:55.799 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:27:00.569 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:27:05.570 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:27:10.497 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:27:15.535 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:38:54.893 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:38:59.483 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:04.482 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:09.489 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:14.569 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:19.488 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:24.494 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:29.510 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:34.536 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:39.488 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:44.552 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:49.635 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:54.554 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:39:59.809 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:40:04.565 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
20:40:09.588 INFO  Ob received and successfully saved into database for ['btcthb', 'eththb', 'dogethb', 'manathb', 'usdtthb', 'adathb', 'sandthb', 'dotthb', 'sushithb', 'galathb', 'yfithb', 'linkthb', 'imxthb', 'nearthb', 'crvthb', 'unithb'] 
